### ISSUE TITLE
日本語

### ISSUE THREAD

**Issue by Astrule** [vosmiic/jellyfin-ani-sync#10]
Hey currently it only syncs anime with English titles, if you could integrate it to work with the original Japanese Title that would be awesome. MyAnimeList & Anilist both have the native title stored somewhere.

This plugin is amazing, thanks so much for making it. If this is not possible I'll gladly change the anime names back to English to keep using it.

**Comment by vosmiic** [comment]
Sure, I see no reason why we couldn't add that.
I'll keep you updated on the progress.
Thanks

**Comment by vosmiic** [comment]
This has now been implemented and pushed to master, unfortunately I could not test it because I could not get Jellyfin to get the Japanese title even after changing the language of my client, but it should be working fine.
You can now either wait for the next update (should be some time early next week) or you can build the plugin off of master and start using it now. I would advise waiting for the update if possible.
If you find it is still not using the Japanese title please do either add a comment to this issue or create a new one.
Thanks

**Comment by Astrule** [comment]
It works, you need the Anilist plugin with the correct series ID for it to update.
Tried 3 series with basically vanilla Jellyfin in Japanese

鬼滅の刃 - Demon Slayer
干物妹!うまるちゃん - Himouto Umaru-Chan
呪術廻戦 - Jujutsu Kaisen

Wouldn't update

I then tested it with an English named anime "Ghost Hunt" and it updated fine, which I though was weird so I installed the AniList plugin thinking maybe some part relied on the ID like the other non-updated one. and tested it with Jujutsu Kaisen again and it worked. So yeah, just install Anilist plugin to save yourself trouble.

**Comment by vosmiic** [comment]
Glad to hear that it is working for you, even if it relies on the Anilist plugin. Thanks for replying with how you got it working to help others who may have this problem
