### ISSUE TITLE
Manual Sync (Jellyfin -> Provider) not respecting "Libraries to check"

### ISSUE THREAD

**Issue by BlakeTech** [vosmiic/jellyfin-ani-sync#114]
**Describe the bug**
From the console, the shows it's scanning to push up to anilist include some that are not in the anime libraries explicitly selected in the upper sections.

**To Reproduce**
Install plugin
Configure client id/secret for anilist
select anime library to check, disable "Plan to watch" and "rewatching" toggles
save
manual sync (cause I can't tell if auto sync even works at all)

**Expected behavior**
It should only scan shows in the specific library as configured above. Also, it should keep trying until it finishes, not randomly stop somewhere without notification. That leads to the sync never completing properly, and multiple reruns don't seem to fix it.

**Desktop (please complete the following information):**
 - Jellyfin version 10.8.13
 - Plugin version 3.0

**Comment by BlakeTech** [comment]
Side note, regarding the random stopping, it seems to happen when the response is too slow from jellyfin. Not sure what the cause is since the hardware's fairly modern (4650g), and when re-running the plugin it seems to look again from the very start instead of some log to keep track.

**Comment by vosmiic** [comment]
>It should only scan shows in the specific library as configured above.

I agree, I'll add this to the todo list.
>Also, it should keep trying until it finishes, not randomly stop somewhere without notification

This is difficult to accomplish as this is a background fire and forget job so it can't notify the user of failures (apart from through the logs), so not much can be done here.

>when re-running the plugin it seems to look again from the very start instead of some log to keep track

This is difficult to keep track of as the plugin is unaware of external changes, since this feature is really designed to only be used once (most install the plugin and then run the manual sync to update their providers, and then the plugin will naturally update any changes after that as you watch shows through Jellyfin) I don't think there is much need to keep track of the progress.

>There are also reports of "too many requests" , so perhaps slow down the process?

I would highly suggest building a version of the plugin from master, as I have just pushed up a commit that fixes this issue due to #109. Its not quite ready for release yet so if you are unable to build a version, there are docker build instructions here or I can build a version with the fix in it for you. 

>Series that show up as none watched are skipped. Is there a way to override that? Or add those as "plan to watch"?

Also a good idea, and can be easily added. I'll add it to the todo list.

**Comment by BlakeTech** [comment]
I think I'll just wait for the plugin to update. I can build it with docker, but i don't know what arguments are needed, and the kubernetes setup that Truenas uses seems rather touchy doing things manually.

**Comment by Mr0Cake** [comment]
If it's not too much work, could you release a beta version?
Otherwise I will look into building it myself because I'm struggling a bit with the anilist sync issue.
Thanks!

**Comment by vosmiic** [comment]
>If it's not too much work, could you release a beta version?
Sure, I'll look into it. There have been a few other fixes so its probably a good time to get a new beta version out

**Comment by vosmiic** [comment]
@Mr0Cake not sure if you saw but there is a new beta version that contains the AniList fixes

**Comment by vosmiic** [comment]
I'll have a look and see why you are hitting into issues with the callback.
Do note that I am away from my dev PC (and will be a for a while) so updates will be slow unfortunately.

**Comment by BlakeTech** [comment]
Finally had time to check back. Unfortunately, jellyfin can't seem to find 3.1, so I am currently unable to test it. Maybe I don't have the beta repo added in, most likely.

**Comment by vosmiic** [comment]
>Finally had time to check back. Unfortunately, jellyfin can't seem to find 3.1, so I am currently unable to test it. Maybe I don't have the beta repo added in, most likely.

Yeah should have said you need the beta plugin manifest enabled, which can be done by following [these instructions](https://github.com/vosmiic/jellyfin-ani-sync?tab=readme-ov-file#development).

>Oh, additionally, is there a way for it to check specific tags for series to skip over when updating?

Not at the moment, but I can have a look at implementing it if its a feature you would like to be added.

**Comment by vosmiic** [comment]
>Yup, the timeout error does indeed still exist too!

Ah okay, I'll create a new issue for this since I think we are straying away from the original issue
