### ISSUE TITLE
Support for Jellyfin 10.9 Unstable Support

### ISSUE THREAD

**Issue by Cebrain** [vosmiic/jellyfin-ani-sync#116]
Hi,
it would be great if you could add Jellyfin 10.9 Unstable Support.
At the moment, the plugin is "not Supported" in the plugin settings and it would be great if we could use it.

**Comment by vosmiic** [comment]
I have just created an unstable manifest here: https://raw.githubusercontent.com/vosmiic/jellyfin-ani-sync/master/unstable-manifest.json
Could you try adding it as a plugin repo (Plugins -> Repositories -> Add -> Copy the above link and name it whatever you like) and see if you still get the same warning/error?
As the plugins are of the same version, Jellyfin probably won't automatically update it. In fact it may not let you install it at all because there will be no version difference, so you may have to re-install the plugin. I'm not sure if uninstalling the plugin removes your config, so its probably best to backup your config file (location of the config file is explained here: https://jellyfin.org/docs/general/server/plugins/) and then restore it after installing the unstable plugin version.
Hopefully this helps, it may still detect that version as the 10.8 version though so fingers crossed it works.

**Comment by vosmiic** [comment]
Hmm unfortunately I am away from my dev PC so I can't really easily test things myself, but you could replicate the same steps as above but instead download the [latest version](https://github.com/vosmiic/jellyfin-ani-sync/releases/tag/v3.0) and extract it to the Jellyfin plugin folder (probably best to put it in its own folder, so something like `plugins/ani-sync-unstable/`) You will also want to edit the `meta.json` file, specifically the `targetAbi` value to equal the version you are running, presumably `10.9.0.0`.

If this doesn't work I can get a 10.9 version of Jellyfin up and running and try to work something out.

**Comment by vosmiic** [comment]
Going to close this as its been some time, if you guys still need some help feel free to re-open the issue
