### ISSUE TITLE
shikimori does not create an application with a redirect to http

### ISSUE THREAD

**Issue by Druidblack** [vosmiic/jellyfin-ani-sync#144]
**Describe the bug**
shikimori does not create an application with a redirect to http

How do I synchronize with shikimori if I use jellyfin only on a local network over http?

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Jellyfin version [e.g. 10.9.7]
 - Plugin version [e.g. 3.3 beta]

**Comment by vosmiic** [comment]
I don't think I quite understand your issue, Shikimori doesn't create an application with a redirect URL, you need to enter your redirect URL which can be generated on the config page (althought the generated URL is not guaranteed to be correct, depending on your specific setup).

Check out the guide on how to auth the plugin with Shikimori: https://github.com/vosmiic/jellyfin-ani-sync/wiki/Providers-Setup#create-app-2

**Comment by Druidblack** [comment]
![Безымянный](https://github.com/vosmiic/jellyfin-ani-sync/assets/70659424/2a480c9b-41c9-4a3c-9143-2547e657c84f)

**Comment by vosmiic** [comment]
Can you confirm there isn't a space character at the start of that redirect URL? Also please make sure there isn't an empty line below the single redirect URL

**Comment by Druidblack** [comment]
https://github.com/vosmiic/jellyfin-ani-sync/assets/70659424/4813d32c-a34e-4c60-88c7-f1cd3742365f

There are no spaces or empty lines .

**Comment by vosmiic** [comment]
Okay, I believe it is because your Jellyfin instance is hosted under HTTP and not HTTPS. I am able to use HTTP locally (using `127.0.0.1` as my IP) but attempting to set the redirect URL as a LAN IP (e.g. `192.168.1.1`) causes the same error you are seeing. I think this security restriction is unique to Shikimori as I don't run into this issue with other providers.
Enabling HTTPS in your Jellyfin server settings should fix the issue.
