### ISSUE TITLE
AniList: Season one updated despite watching later season

### ISSUE THREAD

**Issue by Pecomare** [vosmiic/jellyfin-ani-sync#24]
When an anime has multiple seasons, watching an episode of a later season updates the first season in AniList.

For example, Love Live! Nijigasaki Gakuen School Idol Doukoukai
Here's an excerpt of a log line I added: 
> season: 2, episode: 11, providers: 'Tvdb': '388317', 'AniList': '113970', 'AniDB': '15313', 'Tmdb': '103511', 'Imdb': 'tt12792684'

We can see AniSync knows it's the second season, but the ProviderIds point to the first season. Since the values are in the list, AniSync will update the first season instead of looking up for the second, disregarding the season number.

If we look in anime-list-full.xml, we can see this:
```
<anime anidbid="15313" tvdbid="388317" defaulttvdbseason="1">
  <name>Love Live! Nijigasaki Gakuen School Idol Doukoukai</name>
</anime>
...
<anime anidbid="16310" tvdbid="388317" defaulttvdbseason="2">
  <name>Love Live! Nijigasaki Gakuen School Idol Doukoukai (2022)</name>
</anime>
```
I feel like there is an error in the XML data lookup, as there are 2 entries for the series, one for each season, but it seems like we don't pick the second one.

For information, series in my Jellyfin instance are in the following format:
```
Series
    Love Live! Nijigasaki Gakuen School Idol Doukoukai
        Season 01
            Love Live! Nijigasaki Gakuen School Idol Doukoukai - S01E01 - episode_title.mkv
        Season 02
            Love Live! Nijigasaki Gakuen School Idol Doukoukai - S02E01 - episode_title.mkv
```

Jellyfin Server: 10.8
AniSync: 2.0.1 (also present in latest commit)

**Comment by vosmiic** [comment]
Hmm this was the main reason I released the hotfix, could you please confirm you have it installed?

https://github.com/vosmiic/jellyfin-ani-sync/blob/d88ea1e43970a4c357b0d82a1a95a08f2a01eeb6/UpdateProviderStatus.cs#L87
This specific line should mean that other metadata providers are used if the season is not the first.

**Comment by vosmiic** [comment]
I am testing this and it seems to work for me, and I have the same provider IDs as you. Got to work out what is different in your situation.
I presume you are debugging since you are following the execution path, are you able to see what the values are at this location 
https://github.com/vosmiic/jellyfin-ani-sync/blob/d88ea1e43970a4c357b0d82a1a95a08f2a01eeb6/Helpers/AnimeListHelpers.cs#L30-L31
as for me that contains a single value in the list, which is the 2nd season.

**Comment by vosmiic** [comment]
I believe I have got it working, however it will not actually use the Anidb ID stored, as Jellyfin stores the first season's ID (as you have found out in your original post) only.
However, it will fallback to using the TVDB ID if available which handles seasons a bit better in our situation.
As you can see from my logs, it was able to successfully detect the shows correct season
```
[20:45:05] [INF] [54] jellyfin_ani_sync.UpdateProviderStatus: Anime already has AniDb ID; no need to look it up
[20:45:05] [WRN] [54] jellyfin_ani_sync.UpdateProviderStatus: Anime not found in anime list XML; relying on other metadata providers if available...
[20:45:05] [INF] [54] jellyfin_ani_sync.UpdateProviderStatus: Anime reference found in anime list XML
[20:45:05] [INF] [54] jellyfin_ani_sync.UpdateProviderStatus: Retrieving provider IDs from offline database...
[20:45:06] [INF] [59] jellyfin_ani_sync.UpdateProviderStatus: Retrieved provider IDs
[20:45:06] [INF] [59] jellyfin_ani_sync.UpdateProviderStatus: Using provider AniList...
[20:45:06] [INF] [59] jellyfin_ani_sync.UpdateProviderStatus: (AniList) Series ({{Season 2 of show}}) not found in plan to watch list, checking completed list..
```
Feel like I need to change the order of the provider compatibility wiki page after our recent findings.
The fix is out on master if you want to use the plugin with the fixes immediately, but it will be available in the next release if you have the plugin installed via the manifest.
