### ISSUE TITLE
Plugin seems to change "Ticking" functionality in Jellyfin

### ISSUE THREAD

**Issue by kittenya** [vosmiic/jellyfin-ani-sync#26]
When I have this plugin installed ticking a show in Jellyfin regardless of where I tick it only seems to "tick off" a single episode, default Jellyfin behavior is to tick off the entire show unless you are ticking an episode specifically rather than using the show heading or jellyfin homepage. My use case is that I'm importing hundreds of shows (thousands of episodes) into Jellyfin and clicking the watched "tick" to mark them as watched, ideally that would mark the entire show as completed on my MAL too using this plugin with the option "Ticking watched updates providers?" selected in plugin settings.

**Comment by vosmiic** [comment]
The feature is new and is in a kind of "beta" phase, so it may not work in all scenarios.
Instead of ticking the series as completed as a whole, could you try ticking each season in the series as complete?
It worked for me during testing. Do note that it can take some time depending on how many episodes a show has.

**Comment by kittenya** [comment]
I tried clicking on the season itself like you suggested, behavior seems strange, a single click ticked down one episode at a time marking it as watched on MAL and then when it finishes the series is marked as "rewatching". I think expected behavior would be for it to mark the entire series at once without looping through updating it one episode at a time? And marking the series as "Completed"

**Comment by vosmiic** [comment]
>single click ticked down one episode at a time

When marking episodes as played on mass (by marking the season as played) Jellyfin sends each episode played event separately, so we have to make an API call for each individual episode in the season. This takes some time so seeing them as played in the interface comes with a bit of lag. Not much we can do about this, but I'll have a look.

>marked as "rewatching".

I'm not sure if this is a bug in the plugin or MAL's API, as we don't get this with the other providers. It also occurs when watching a season fully naturally (without manually marking them as played). 
I will take a look at the issues once I have completed my current work.

**Comment by vosmiic** [comment]
I believe I have worked out the problem.
The API (this isn't a problem with AniList or Kitsu) seems to interpret that "if the value is in the body of the call, it must be true no matter what it has been set to".
We send a "is_rewatching" value on most calls. Unfortunately it looks like the API interprets this as `true` even if we populate it with `false`.
I am working around this by simply not setting the value on the call if we are not re-watching the media.
However this does not fix the problem if you are re-watching something and finish it. Unfortunately it will show as completed but re-watching, and will need to be manually un-ticked by the user via the frontend.
This should fix the issue in your case though.
The fix is currently out on master, but will be included in the next release.
Thanks for letting me know of the issue, and if you continue to have problems please do let me know.
