### ISSUE TITLE
"Could not update anime list" error?

### ISSUE THREAD

**Issue by Andy2244** [vosmiic/jellyfin-ani-sync#28]
Seeing this on windows? Check the creation flags to allow overrides or maybe use a rename, create logic?
```
IntervalTrigger fired for task: AniSync Update Anime List
[INF] [124] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task TaskUpdateAnimeList
[INF] [124] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing AniSync Update Anime List
[ERR] [128] jellyfin_ani_sync.TaskUpdateAnimeList: Could not update anime list; Cannot create 'd:\_configs\jellyfin\cache\ani-sync\anime-list-full.xml' because a file or directory with the same name already exists.
[INF] [128] Emby.Server.Implementations.ScheduledTasks.TaskManager: AniSync Update Anime List Completed after 0 minute(s) and 0 seconds
```

**Comment by Andy2244** [comment]
I deleted my custom location and left the setting empty than restarted the server and i got this:
`jellyfin_ani_sync.TaskUpdateAnimeList: Could not update anime list; Access to the path 'd:\_configs\jellyfin\cache\anisync\anime-list-full.xml' is denied.`

I check the location and found that the plugin created a folder instead of a file?
`d:\_configs\jellyfin\cache\anisync\anime-list-full.xml\`

So `\anime-list-full.xml\` should be a file not a folder?

**Comment by vosmiic** [comment]
This is why I shy away from dealing with files, Windows and Linux seem to handle things very differently.
I'm not entirely sure why you are getting a `Cannot create` error since we use `FileMode.OpenOrCreate` which signifies either open the file if it exists or create it if it does not:
https://github.com/vosmiic/jellyfin-ani-sync/blob/82f1da90c910e16938c80b7f3ed635330ded8ab8/Tasks/UpdateAnimeList.cs#L75
Also not sure why it is creating a folder when the custom location settings is empty, it is supposed to detect when the setting is an empty string and use the default folder.
I'll get it spun up on my Windows machine and have a look.

**Comment by vosmiic** [comment]
Okay, fixed it.
Turns out its because of this line:
https://github.com/vosmiic/jellyfin-ani-sync/blob/82f1da90c910e16938c80b7f3ed635330ded8ab8/Tasks/UpdateAnimeList.cs#L73
That would work on Linux because paths are represented with slashes, so `here/is/a/path`.
However Windows handles paths with a _backslash_, so `here\is\a\path`.
I have now changed it so it doesn't matter which OS is being used:
https://github.com/vosmiic/jellyfin-ani-sync/blob/e6dee63f82f60623b67156c21d7d7cfd5393c9fa/Tasks/UpdateAnimeList.cs#L73
I have tested it on my Windows machine and its now working (I was getting the same issues as you).
The update is on master, but as always the fix will be out in the next release.
