### ISSUE TITLE
Made in Abyss: The Golden City of the Scorching Sun not tracking

### ISSUE THREAD

**Issue by reitenth** [vosmiic/jellyfin-ani-sync#35]
The plugin is not updating this on Anilist whenever I finish an episode for some reason and I have to manually do it. This is the Anilist id: 114745. Here is a ss of my Jellyfin library. Might be because it has a unique title compared to just "Made in Abyss." Thanks!

![image](https://user-images.githubusercontent.com/94771708/182939201-644d7ae2-6d21-484a-901b-51f21951a9b9.png)

**Comment by vosmiic** [comment]
Hi
As you said, it is because it does not have a unique title. I would attempt to manually change the item (click on the three dots, "Identify" and search for the title) and then try again. Just gave it a quick test myself and I can see that you can change it to the appropriate title when using AniList as a metadata provider.
The plugin can only work with what it is presented with from Jellyfin, if you have an item in your library that is labelled "Made in Abyss" it will presume you are indeed watching "Made in Abyss" season 2.
If you continue to have trouble after manually changing the item, please do re-open this issue and I should be able to help you out.
