### ISSUE TITLE
Anilist Authentication Fails

### ISSUE THREAD

**Issue by jruaaa** [vosmiic/jellyfin-ani-sync#36]
When authenticating I see the following error:

`{"error":"invalid_client","message":"Client authentication failed"}`

I'm using a subdirectory as the baseURL but the test url still returns the correct verbiage. I'm running Jellyfin in docker so I can't easily see the logs and whatnot, so I have no idea what the cause of this error is. The API secrets and ID's all check out on the website but this could be similar to #25 where the xml doesn't have the correct values. Do you know if I could try inspecting the website and see if the values are stored in a place that is easier to access?

![image](https://user-images.githubusercontent.com/32626650/193476901-24eda021-a0c8-401d-9798-943534e6deca.png)

**Comment by vosmiic** [comment]
Hi, so the issue with the referenced pull request is that the client ID that was entered started with a space. I would first off make sure that your client ID and secret both don't start with a space or having a trailing space, or other character.
One you have confirmed that there are no trailing characters, I would first off inspect the URL generated when clicking on the authorize button. Does the client ID and secret look correct? 
Also try navigating to the callback URL appended to the auth request URL, it should throw back a 400 "the code field is required" error. 
After that checking the config xml would be the best bet, which I know is difficult since you are running Jellyfin in Docker. 
I personally run Jellyfin as a raw service, and I generally don't have much to do with Docker so I can't offer much assistance, but hopefully [this article](https://jhooq.com/docker-edit-file-inside-container/) might help (I would first `cat` the config file instead of editing it).
Also how far into the authentication do you get before you hit that error? After you login and accept the integration on the AniList website?

**Comment by BobbyWibowo** [comment]
I was able to resolve this issue on my end by creating a new AniList client
**But** one thing to note was that, the Redirect URL input during client creation, must immediately be filled with your proper URL
![image](https://i.fiery.me/L2BV.png)

The AniList client with which I was having issue, I initially created with empty Redirect URL
AniList would then pre-fill it with `null` after being created, which seemed all fine and dandy
However, despite editing the client details to enter the proper Redirect URL, it was still no good
It only worked immediately for me after creating a new one, with Redirect URL filled during creation

**Comment by vosmiic** [comment]
Thanks for your insight @BobbyWibowo, hopefully this has helped @jruaaa to fix their issue.
I am going to close this as it has been inactive for some time, but please do re-open it if you continue to hit into this issue.
Thanks!
