### ISSUE TITLE
Status: NotSupported (Maybe it's me who doesn't understand)

### ISSUE THREAD

**Issue by Sky-NiniKo** [vosmiic/jellyfin-ani-sync#37]
Disclaimer: I don't know how to use this plugin even after reading the documentation several times.
# The issue
Hi, I'm trying to setup jellyfin-ani-sync, so I add your repo and install the plugin. I restarted several times but I still have the same problem.
`Status: NotSupported`
![image](https://user-images.githubusercontent.com/61370893/194695060-ea1db2a7-1de0-4c12-a3b1-dade8fc450b8.png)

I'm a bit lost. Also, when I click on the plugin to configure it, I get this error.
![image](https://user-images.githubusercontent.com/61370893/194695074-37f13df3-7603-40bc-a645-6a118c149c8f.png)

# I don't know if it's related
I'm using a Raspberry Pi 4, I don't know if it's an architecture problem, or something else.

Thanks in advance if anyone knows what I am doing wrong.

**Comment by vosmiic** [comment]
Hi, generally that error means that the plugin version is not supported by your Jellyfin version.
Which Jellyfin version are you running? You may have to install an older version of the plugin.
Checking the logs of the server should also help to work out why that error is occurring (should be near the top of the logs after starting Jellyfin, when the plugins are initialized)

**Comment by vosmiic** [comment]
I just updated my Jellyfin server up to the latest version (the same as yours), and the plugin still runs fine. Odd.
Anyway the issue seems to be that the libraries that we use are out of date in the plugin, I have updated them and have released a new version.
All you need to do is update your plugin via the scheduled tasks, and restart your Jellyfin server.
Do let me know if this has not fixed your issue, thanks.
