### ISSUE TITLE
annict support

### ISSUE THREAD

**Issue by sakuraimikoto33** [vosmiic/jellyfin-ani-sync#48]
Please support annict.
There is also a tool to synchronize viewing history from annict to anlist, but there is a problem with accuracy. Additionally, you have to sync manually.

**Comment by vosmiic** [comment]
Hi, had a quick look around and can see they have a web API so this should be doable.
I'll add it to the todo list and keep you updated on the progress.

**Comment by vosmiic** [comment]
After some testing, it appears the API search functionality is limited to only accepting Kana; would this be a problem? You would need to have all of your anime in Kana in Jellyfin. I have tried to use English but no results are found.

**Comment by sakuraimikoto33** [comment]
There is no problem with using Kana in my media management.

**Comment by vosmiic** [comment]
Quick question, am I right in thinking that you only update the series once you have finished watching the entire season (by setting the status as complete)? It seems that you cannot (at least from my limited exploration) set each episode as complete, like you can with other services (AniList, MAL).

**Comment by sakuraimikoto33** [comment]
Yes, I don't need the settings for each episode.

It would be helpful if the annict status was set to "watching" when one or more of the season's play completed, and
It would be helpful if the status is set to "complete" in annict when all play of a season is finished.
I would like the status of titles that are "complete" in annict not to be updated.

I'm using a translation tool, so I'm sorry if there are strange English.

**Comment by vosmiic** [comment]
>I'm using a translation tool, so I'm sorry if there are strange English.

I completely understand you, no issues 😄 

I have just released a new version of the plugin which contains the support for Annict, it works quite differently to the other support providers and is not as reliable so you may find it won't update an anime (or it may attempt to update an incorrect anime), unfortunately there isn't much that can be done to fix this due to the nature of the Annict API.

I am going to write up some documentation and then edit this post with a link to them to get you started.

If you hit into any problems using the plugin, please do create an issue and I will get back to you.
