### ISSUE TITLE
Doesn't detect if using display order DVD

### ISSUE THREAD

**Issue by ACViper** [vosmiic/jellyfin-ani-sync#55]
There are certain series like Monogatari, where display order "aired" only shows 5 seasons and has the rest of the episodes under "Specials." Using display order "DVD" it list the proper 10 seasons with all the episodes under the correct seasons. 

This is an issue because ani-sync only uses the default display order, which is "aired." It doesn't know if something is under display order "DVD." This leads to the wrong season episode being synced (ex. s05e01 is being marked read, but s07e01 gets synced in mal/anilist). I am using the TVDB plugin.

**Comment by vosmiic** [comment]
Hi, this sounds like a metadata issue. The plugin can only deal with the information that it is given either by Jellyfin or the external databases.
I know for a fact that the Monogatari series has quite a complicated watch order when it comes to the providers (Jellyfin stores the correct season e.g. Kabukimonogatari, but MAL might have it under "Monogatari Season 2" which causes incorrect updates, as you have experienced). 
Unless we create an exception list for certain "complicated" anime, which will have to be manually managed which I am not personally going to do, there isn't much that can be done about these issues.
When I watched the Monogatari series I ended up disabling the plugin and manually updating the providers because it was causing a lot of updating issues.
Apologies, but without a lot of work, this can't be fixed.
