### ISSUE TITLE
Running manual sync works but scheduled task doesn't

### ISSUE THREAD

**Issue by carloslos** [vosmiic/jellyfin-ani-sync#58]
Hello, I'm running into this issue in which if I run the manual sync the plugin works, both from and to AniList; but the scheduled task, either waiting for it to happen or running it by clicking the play button, doesn't do anything at all, the log just says:

[2023-02-01 01:54:08.092 +01:00] [INF] [26] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "AniSync Update Anime List"
[2023-02-01 01:54:08.355 +01:00] [INF] [20] Emby.Server.Implementations.ScheduledTasks.TaskManager: "AniSync Update Anime List" Completed after 0 minute(s) and 0 seconds
[2023-02-01 01:54:08.357 +01:00] [INF] [20] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks

I do wonder if it's something I've done wrong or not, but considering that the manual sync does work I don't get what else I can do.

Thanks in advanced.

**Comment by carloslos** [comment]
Seems to be working now even though I changed nothing, thanks anyway.

**Comment by vosmiic** [comment]
Hi,
That scheduled job is to refresh the locally stored anime list every so often, it does not do any syncing of any kind.
As the library sync requires arguments, it would be difficult to add a scheduled task to do this.
Thanks

**Comment by carloslos** [comment]
> Hi, That scheduled job is to refresh the locally stored anime list every so often, it does not do any syncing of any kind. As the library sync requires arguments, it would be difficult to add a scheduled task to do this. Thanks

That might have been it then, I may have been not patient enough to test the automatic sync properly.
Thanks for the reply!

**Comment by clean-interaction** [comment]
Hey, my problem is similar to this so I didn't wanna create a new issue.
Manual sync works but it doesn't automatically update anilist. 
Yesterday, I was having trouble getting it to sync(maybe important piece of info idk but I haven't used jellyfin for a long time since setting it up with this plugin) so I ran the manual sync and it updated anilist just fine. It continued to automatically update watched episodes to anilist after that for the rest of the day.
But, today it isn't working again. (Servers was shut down and started again). 
(Hopefully) relevant log:

`Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://localhost:8096/AniSync/user?apiName=AniList&userId=e762d8341c114406a34b2e36226c4714" to "127.0.0.1" in 0:00:00.8007387 with Status Code 200`
