### ISSUE TITLE
SPY x FAMILY  sync problem

### ISSUE THREAD

**Issue by garvongithub** [vosmiic/jellyfin-ani-sync#72]
### Details
SPY x FAMILY released in 2 parts. On anilist there are 2 entries ([Original](https://anilist.co/anime/140960/SPY-x-FAMILY/) and [2nd part](https://anilist.co/anime/142838/SPY-x-FAMILY-Cour-2/)). On TVDB, they are combined as [[1 season ](https://thetvdb.com/series/spy-x-family/seasons/official/1)]. This has lead to a problem. After completing the episode of cour 2, plug in syncs the progress to the original entry which only has 12 episodes, but it should sync to cour 2. Can this be fixed please?.

### Supposed behavior
![image](https://github.com/vosmiic/jellyfin-ani-sync/assets/77321589/d8d1c5e7-5b38-4c20-82c9-4dba3d6026d6)
Done Manually by me after watching

### Actual Behavior
![image](https://github.com/vosmiic/jellyfin-ani-sync/assets/77321589/426b6bc9-c32d-42a0-9298-090349555eb0)

### Metadata Setup
![image](https://github.com/vosmiic/jellyfin-ani-sync/assets/77321589/878fca1f-58c2-42c8-8a3a-9fbaa71549a9)

**Comment by vosmiic** [comment]
Does this only occur in this show, or are you finding its incorrectly updating all other anime you have in your library? We can't fix specific anime, unfortunately due to the nature of how we detect anime it will not always be 100% accurate.

**Comment by garvongithub** [comment]
From my usage, I can say this only happens in this show, everything else works fine, but also this is the only show I have watched since setting up the plugin which has different no entries on different sites.

**Comment by vosmiic** [comment]
Its probably only this show. If you check out some of the old issues of the repository you will find a few others that have found some edge cases where the plugin will not work with certain shows. I'm going to close the issue but if you find that the same thing is happening for all of the anime in your library please do open another issue. Thanks

**Comment by forerser** [comment]
Hello @vosmiic do you have a discord server to discuss this sync problems? to not create and issue for every show.

**Comment by vosmiic** [comment]
There isn't a discord server, and I don't have any plans on creating one. If you notice that multiple shows/movies are incorrectly updating, please do just create an issue. It may be due to a different issue.

**Comment by funforgiven** [comment]
Sync problems are actually not directly related to jellyfin-ani-sync but [anime-lists](https://github.com/Anime-Lists/anime-lists) and [anime-offline-database](https://github.com/manami-project/anime-offline-database), usually anime-lists. You can always create pull requests on anime-lists project to fix id, season and offset data. I also suggest not enabling AniList metadata provider because it usually does not detect correctly, which is probably your problem here since anime-lists season and offset is actually correct at the time of you posting this. Only enable TVDB and jellyfin-ani-sync will map it to AniDB id using anime-lists and then get the AniList ID from anime-offline-database using obtained AniDB id.

Also, if you don't want to depend on anime-lists project and/or TVDB, you can use Shoko. It hashes your anime files and compares it to AniDB database to detect its AniDB entry and episode. It is very reliable and jellyfin-ani-sync will skip anime-lists and will only use anime-offline-database to get AniList id.

**Comment by sannidhyaroy** [comment]
I experienced this exact behavior with Spy x Family. I watched episode 13 (according to TVDB), but AniList has it as it as episode 1 of Cour 2, so it syncs the incorrect info to AniList. Sonarr uses [TheXEM](thexem.info) to properly recognize episodes due to this confusion. Can Ani-Sync use something similar?
