### ISSUE TITLE
[Feature Request] Ability to configure a custom redirect after a successful authentication.

### ISSUE THREAD

**Issue by throwabird** [vosmiic/jellyfin-ani-sync#83]
After authenticating with MAL, users are redirected to `AniSync/authCallback?code=[...]` which just shows them a blank page.
I'd like to have a configuration option to redirect the user further if the authentication was successful. A simple usecase for this is to simply redirect them back to the main page of jellyfin, so they dont get confused by the blank page, which could be the default configuration.
I would love for it to be configurable, since I'd like to redirect my users back to a service-desk where they received the authentication link.

**Comment by vosmiic** [comment]
Sounds like a good idea, will add it to my list of things to investigate 👍

**Comment by vosmiic** [comment]
So this has now been implemented on the mentioned PR, a few notes on how it works:

- There are a few variables available. `{{LocalIpAddress}}` converts to the local IP address of the Jellyfin instance, and `{{LocalPort}}` converts to the port of the Jellyfin instance. Hopefully helpful if your IP and/or port is dynamic.
- The redirect will only work if the authentication is successful. Otherwise you will get a 500 and the error will be logged.
- If the supplied URL is not valid no redirect will occur, you will receive the old blank 200 page.

The above will be added to the wiki but thought I may as well include the details here as well. Does this fulfil your needs?

**Comment by throwabird** [comment]
Yes, this sounds perfect. Thank you very much!

**Comment by vosmiic** [comment]
No problem. So the PR has been merged into master, you can either build the plugin if you would like the changes immediately or wait for the next plugin release and Jellyfin will automatically update the plugin for you.
