### ISSUE TITLE
Episode number incorrect for series with multiple seasons.

### ISSUE THREAD

**Issue by AnthonySchneider2000** [vosmiic/jellyfin-ani-sync#87]
**Description**
For anime with multiple seasons, the current episode may be detected incorrectly if the episode count is based on the total series episodes instead of the current season's episodes.
Ex. Jujutsu Kaisen Episode 36 sets Anilist's progress to 36/23 instead of 13/23.
I'm not certain what their implementation is, but I know Taiga didn't have this issue.

**Environment:**
 - Client: Swiftfin for Apple TV
 - Jellyfin version: 10.8.11
 - Plugin version: 2.9

**Comment by rodhfr** [comment]
I'm fairly certain this this happened because of metadata providers. If you take a look at TMDB there is just [Jujutsu Kaisen](https://www.themoviedb.org/tv/95479) (2020) with 47 episodes while myanimelist splits with two entries, [first](https://myanimelist.net/anime/40748/Jujutsu_Kaisen) and [second](https://myanimelist.net/anime/51009/Jujutsu_Kaisen_2nd_Season?cat=anime) seasons.

**Comment by vosmiic** [comment]
Please provide the appropriate Jellyfin logs when this happened. It should attempt to search for a second season/cour if the episode count is greater than the season it detects.
Also as @rodhfr said, this is more than likely a metadata provider issue. Check out the wiki for the best metadata providers to use with the plugin: https://github.com/vosmiic/jellyfin-ani-sync/wiki/Metadata-Downloader-Compatibility
Also we do not fix individual media issues, so if the issue is tied to that specific anime there isn't much that will be done to fix it.
